include:
  remote: "https://github.com/git-developer/docker-support/raw/feature/gitlab-ci/gitlab-ci/docker-template.yml"

variables:
  IMAGE_TITLE: 'Asset UPnP'
  IMAGE_PLATFORMS: 'linux/amd64,linux/i386,linux/arm/v7'
  APPLICATION_URL: 'http://www.dbpoweramp.com/install/AssetUPnP-Linux-x86.tar.gz'

stages:
  - setup
  - prepare
  - analyze
  - publish

Collect Additional Tags:
  extends: .docker_support:.with_bare_image
  stage: analyze
  artifacts:
    paths:
    - tags
    - labels
  script:
  - set -euo pipefail
  - run() { docker run --rm "${IMAGE_NAME}:${BUILD_CACHE}" sh -c "${@}"; }

  - APP_VERSION="$(run 'cat "$(dirname $(readlink -f /usr/bin/asset))/Versions/Asset-UPnP.txt"')"
  - APP_DATE="$(run 'stat -L -c %y "$(dirname $(readlink -f /usr/bin/asset))/Versions/Asset-UPnP.txt"' | cut -d ' ' -f 1)"
  - BUILD_ID="$(date -u +%Y%m%d_%H%M%S)-${IMAGE_REVISION:-${CI_COMMIT_SHORT_SHA}}-$(od -An -N5 -tu4 </dev/urandom | tr -d ' ' | head -c8)"

  - mkdir -p tags
  - echo >tags/app_version "${IMAGE_NAME}:${APP_VERSION}"
  - echo >tags/app_date "${IMAGE_NAME}:${APP_DATE}"
  - echo >tags/build_id "${IMAGE_NAME}:b${BUILD_ID}"

  - oci='org.opencontainers.image'
  - mkdir -p labels
  - echo >"labels/${oci}.version" "${oci}.version=${APP_VERSION}"
